version: "3"

services:
  sanic:
    #restart: always
    stdin_open: true
    tty: true
    build: ./
    volumes:
    #  - /home/xuqinghan/dev/flask_test:/code
      - ./app:/code
    ports:
      - "8000:8000"
    command: ['python3', 'main.py']

  # flask:
  #   #restart: always
  #   stdin_open: true
  #   tty: true
  #   build: ./
  #   volumes:
  #     - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
  #     - ./app:/code
  #   ports:
  #     - "8001:8001"
  #   # command: '/usr/bin/supervisord'
  #   command: ['gunicorn','-w 4','-b 0.0.0.0:8001','mainflask:app']
